// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ItemProto.proto

package proto;

public final class ItemProto {
  private ItemProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BuyReq_1001000OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 cfg_id = 1;
    /**
     * <code>required int32 cfg_id = 1;</code>
     *
     * <pre>
     *物品配置id
     * </pre>
     */
    boolean hasCfgId();
    /**
     * <code>required int32 cfg_id = 1;</code>
     *
     * <pre>
     *物品配置id
     * </pre>
     */
    int getCfgId();
  }
  /**
   * Protobuf type {@code protoFiles.BuyReq_1001000}
   *
   * <pre>
   * 买
   * </pre>
   */
  public static final class BuyReq_1001000 extends
      com.google.protobuf.GeneratedMessage
      implements BuyReq_1001000OrBuilder {
    // Use BuyReq_1001000.newBuilder() to construct.
    private BuyReq_1001000(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BuyReq_1001000(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BuyReq_1001000 defaultInstance;
    public static BuyReq_1001000 getDefaultInstance() {
      return defaultInstance;
    }

    public BuyReq_1001000 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BuyReq_1001000(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              cfgId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.ItemProto.internal_static_protoFiles_BuyReq_1001000_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.ItemProto.internal_static_protoFiles_BuyReq_1001000_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.ItemProto.BuyReq_1001000.class, proto.ItemProto.BuyReq_1001000.Builder.class);
    }

    public static com.google.protobuf.Parser<BuyReq_1001000> PARSER =
        new com.google.protobuf.AbstractParser<BuyReq_1001000>() {
      public BuyReq_1001000 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BuyReq_1001000(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BuyReq_1001000> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 cfg_id = 1;
    public static final int CFG_ID_FIELD_NUMBER = 1;
    private int cfgId_;
    /**
     * <code>required int32 cfg_id = 1;</code>
     *
     * <pre>
     *物品配置id
     * </pre>
     */
    public boolean hasCfgId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 cfg_id = 1;</code>
     *
     * <pre>
     *物品配置id
     * </pre>
     */
    public int getCfgId() {
      return cfgId_;
    }

    private void initFields() {
      cfgId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCfgId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, cfgId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cfgId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static proto.ItemProto.BuyReq_1001000 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ItemProto.BuyReq_1001000 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ItemProto.BuyReq_1001000 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ItemProto.BuyReq_1001000 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ItemProto.BuyReq_1001000 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.ItemProto.BuyReq_1001000 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.ItemProto.BuyReq_1001000 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.ItemProto.BuyReq_1001000 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.ItemProto.BuyReq_1001000 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.ItemProto.BuyReq_1001000 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.ItemProto.BuyReq_1001000 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoFiles.BuyReq_1001000}
     *
     * <pre>
     * 买
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements proto.ItemProto.BuyReq_1001000OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.ItemProto.internal_static_protoFiles_BuyReq_1001000_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.ItemProto.internal_static_protoFiles_BuyReq_1001000_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.ItemProto.BuyReq_1001000.class, proto.ItemProto.BuyReq_1001000.Builder.class);
      }

      // Construct using proto.ItemProto.BuyReq_1001000.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        cfgId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.ItemProto.internal_static_protoFiles_BuyReq_1001000_descriptor;
      }

      public proto.ItemProto.BuyReq_1001000 getDefaultInstanceForType() {
        return proto.ItemProto.BuyReq_1001000.getDefaultInstance();
      }

      public proto.ItemProto.BuyReq_1001000 build() {
        proto.ItemProto.BuyReq_1001000 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.ItemProto.BuyReq_1001000 buildPartial() {
        proto.ItemProto.BuyReq_1001000 result = new proto.ItemProto.BuyReq_1001000(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cfgId_ = cfgId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.ItemProto.BuyReq_1001000) {
          return mergeFrom((proto.ItemProto.BuyReq_1001000)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.ItemProto.BuyReq_1001000 other) {
        if (other == proto.ItemProto.BuyReq_1001000.getDefaultInstance()) return this;
        if (other.hasCfgId()) {
          setCfgId(other.getCfgId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCfgId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.ItemProto.BuyReq_1001000 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.ItemProto.BuyReq_1001000) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 cfg_id = 1;
      private int cfgId_ ;
      /**
       * <code>required int32 cfg_id = 1;</code>
       *
       * <pre>
       *物品配置id
       * </pre>
       */
      public boolean hasCfgId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 cfg_id = 1;</code>
       *
       * <pre>
       *物品配置id
       * </pre>
       */
      public int getCfgId() {
        return cfgId_;
      }
      /**
       * <code>required int32 cfg_id = 1;</code>
       *
       * <pre>
       *物品配置id
       * </pre>
       */
      public Builder setCfgId(int value) {
        bitField0_ |= 0x00000001;
        cfgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 cfg_id = 1;</code>
       *
       * <pre>
       *物品配置id
       * </pre>
       */
      public Builder clearCfgId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cfgId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protoFiles.BuyReq_1001000)
    }

    static {
      defaultInstance = new BuyReq_1001000(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protoFiles.BuyReq_1001000)
  }

  public interface BuyResp_1001000OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 code = 1;
    /**
     * <code>required int32 code = 1;</code>
     *
     * <pre>
     *code
     * </pre>
     */
    boolean hasCode();
    /**
     * <code>required int32 code = 1;</code>
     *
     * <pre>
     *code
     * </pre>
     */
    int getCode();
  }
  /**
   * Protobuf type {@code protoFiles.BuyResp_1001000}
   */
  public static final class BuyResp_1001000 extends
      com.google.protobuf.GeneratedMessage
      implements BuyResp_1001000OrBuilder {
    // Use BuyResp_1001000.newBuilder() to construct.
    private BuyResp_1001000(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BuyResp_1001000(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BuyResp_1001000 defaultInstance;
    public static BuyResp_1001000 getDefaultInstance() {
      return defaultInstance;
    }

    public BuyResp_1001000 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BuyResp_1001000(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              code_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.ItemProto.internal_static_protoFiles_BuyResp_1001000_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.ItemProto.internal_static_protoFiles_BuyResp_1001000_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.ItemProto.BuyResp_1001000.class, proto.ItemProto.BuyResp_1001000.Builder.class);
    }

    public static com.google.protobuf.Parser<BuyResp_1001000> PARSER =
        new com.google.protobuf.AbstractParser<BuyResp_1001000>() {
      public BuyResp_1001000 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BuyResp_1001000(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BuyResp_1001000> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 code = 1;
    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>required int32 code = 1;</code>
     *
     * <pre>
     *code
     * </pre>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 code = 1;</code>
     *
     * <pre>
     *code
     * </pre>
     */
    public int getCode() {
      return code_;
    }

    private void initFields() {
      code_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, code_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static proto.ItemProto.BuyResp_1001000 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ItemProto.BuyResp_1001000 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ItemProto.BuyResp_1001000 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ItemProto.BuyResp_1001000 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ItemProto.BuyResp_1001000 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.ItemProto.BuyResp_1001000 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.ItemProto.BuyResp_1001000 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.ItemProto.BuyResp_1001000 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.ItemProto.BuyResp_1001000 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.ItemProto.BuyResp_1001000 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.ItemProto.BuyResp_1001000 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoFiles.BuyResp_1001000}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements proto.ItemProto.BuyResp_1001000OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.ItemProto.internal_static_protoFiles_BuyResp_1001000_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.ItemProto.internal_static_protoFiles_BuyResp_1001000_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.ItemProto.BuyResp_1001000.class, proto.ItemProto.BuyResp_1001000.Builder.class);
      }

      // Construct using proto.ItemProto.BuyResp_1001000.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.ItemProto.internal_static_protoFiles_BuyResp_1001000_descriptor;
      }

      public proto.ItemProto.BuyResp_1001000 getDefaultInstanceForType() {
        return proto.ItemProto.BuyResp_1001000.getDefaultInstance();
      }

      public proto.ItemProto.BuyResp_1001000 build() {
        proto.ItemProto.BuyResp_1001000 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.ItemProto.BuyResp_1001000 buildPartial() {
        proto.ItemProto.BuyResp_1001000 result = new proto.ItemProto.BuyResp_1001000(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.code_ = code_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.ItemProto.BuyResp_1001000) {
          return mergeFrom((proto.ItemProto.BuyResp_1001000)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.ItemProto.BuyResp_1001000 other) {
        if (other == proto.ItemProto.BuyResp_1001000.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.ItemProto.BuyResp_1001000 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.ItemProto.BuyResp_1001000) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 code = 1;
      private int code_ ;
      /**
       * <code>required int32 code = 1;</code>
       *
       * <pre>
       *code
       * </pre>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 code = 1;</code>
       *
       * <pre>
       *code
       * </pre>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>required int32 code = 1;</code>
       *
       * <pre>
       *code
       * </pre>
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 code = 1;</code>
       *
       * <pre>
       *code
       * </pre>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protoFiles.BuyResp_1001000)
    }

    static {
      defaultInstance = new BuyResp_1001000(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protoFiles.BuyResp_1001000)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protoFiles_BuyReq_1001000_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protoFiles_BuyReq_1001000_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protoFiles_BuyResp_1001000_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protoFiles_BuyResp_1001000_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ItemProto.proto\022\nprotoFiles\" \n\016BuyReq_" +
      "1001000\022\016\n\006cfg_id\030\001 \002(\005\"\037\n\017BuyResp_10010" +
      "00\022\014\n\004code\030\001 \002(\005B\022\n\005protoB\tItemProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protoFiles_BuyReq_1001000_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protoFiles_BuyReq_1001000_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protoFiles_BuyReq_1001000_descriptor,
              new java.lang.String[] { "CfgId", });
          internal_static_protoFiles_BuyResp_1001000_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protoFiles_BuyResp_1001000_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protoFiles_BuyResp_1001000_descriptor,
              new java.lang.String[] { "Code", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
