// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SyncProto.proto

package proto;

public final class SyncProto {
  private SyncProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PingReq_1001000OrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code protoFiles.PingReq_1001000}
   *
   * <pre>
   * 心跳
   * </pre>
   */
  public static final class PingReq_1001000 extends
      com.google.protobuf.GeneratedMessage
      implements PingReq_1001000OrBuilder {
    // Use PingReq_1001000.newBuilder() to construct.
    private PingReq_1001000(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PingReq_1001000(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PingReq_1001000 defaultInstance;
    public static PingReq_1001000 getDefaultInstance() {
      return defaultInstance;
    }

    public PingReq_1001000 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PingReq_1001000(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.SyncProto.internal_static_protoFiles_PingReq_1001000_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.SyncProto.internal_static_protoFiles_PingReq_1001000_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.SyncProto.PingReq_1001000.class, proto.SyncProto.PingReq_1001000.Builder.class);
    }

    public static com.google.protobuf.Parser<PingReq_1001000> PARSER =
        new com.google.protobuf.AbstractParser<PingReq_1001000>() {
      public PingReq_1001000 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PingReq_1001000(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PingReq_1001000> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static proto.SyncProto.PingReq_1001000 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.SyncProto.PingReq_1001000 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.SyncProto.PingReq_1001000 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.SyncProto.PingReq_1001000 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.SyncProto.PingReq_1001000 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.SyncProto.PingReq_1001000 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.SyncProto.PingReq_1001000 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.SyncProto.PingReq_1001000 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.SyncProto.PingReq_1001000 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.SyncProto.PingReq_1001000 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.SyncProto.PingReq_1001000 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoFiles.PingReq_1001000}
     *
     * <pre>
     * 心跳
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements proto.SyncProto.PingReq_1001000OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.SyncProto.internal_static_protoFiles_PingReq_1001000_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.SyncProto.internal_static_protoFiles_PingReq_1001000_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.SyncProto.PingReq_1001000.class, proto.SyncProto.PingReq_1001000.Builder.class);
      }

      // Construct using proto.SyncProto.PingReq_1001000.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.SyncProto.internal_static_protoFiles_PingReq_1001000_descriptor;
      }

      public proto.SyncProto.PingReq_1001000 getDefaultInstanceForType() {
        return proto.SyncProto.PingReq_1001000.getDefaultInstance();
      }

      public proto.SyncProto.PingReq_1001000 build() {
        proto.SyncProto.PingReq_1001000 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.SyncProto.PingReq_1001000 buildPartial() {
        proto.SyncProto.PingReq_1001000 result = new proto.SyncProto.PingReq_1001000(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.SyncProto.PingReq_1001000) {
          return mergeFrom((proto.SyncProto.PingReq_1001000)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.SyncProto.PingReq_1001000 other) {
        if (other == proto.SyncProto.PingReq_1001000.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.SyncProto.PingReq_1001000 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.SyncProto.PingReq_1001000) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protoFiles.PingReq_1001000)
    }

    static {
      defaultInstance = new PingReq_1001000(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protoFiles.PingReq_1001000)
  }

  public interface PongResp_1001000OrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code protoFiles.PongResp_1001000}
   */
  public static final class PongResp_1001000 extends
      com.google.protobuf.GeneratedMessage
      implements PongResp_1001000OrBuilder {
    // Use PongResp_1001000.newBuilder() to construct.
    private PongResp_1001000(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PongResp_1001000(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PongResp_1001000 defaultInstance;
    public static PongResp_1001000 getDefaultInstance() {
      return defaultInstance;
    }

    public PongResp_1001000 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PongResp_1001000(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.SyncProto.internal_static_protoFiles_PongResp_1001000_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.SyncProto.internal_static_protoFiles_PongResp_1001000_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.SyncProto.PongResp_1001000.class, proto.SyncProto.PongResp_1001000.Builder.class);
    }

    public static com.google.protobuf.Parser<PongResp_1001000> PARSER =
        new com.google.protobuf.AbstractParser<PongResp_1001000>() {
      public PongResp_1001000 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PongResp_1001000(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PongResp_1001000> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static proto.SyncProto.PongResp_1001000 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.SyncProto.PongResp_1001000 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.SyncProto.PongResp_1001000 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.SyncProto.PongResp_1001000 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.SyncProto.PongResp_1001000 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.SyncProto.PongResp_1001000 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.SyncProto.PongResp_1001000 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.SyncProto.PongResp_1001000 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.SyncProto.PongResp_1001000 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.SyncProto.PongResp_1001000 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.SyncProto.PongResp_1001000 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoFiles.PongResp_1001000}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements proto.SyncProto.PongResp_1001000OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.SyncProto.internal_static_protoFiles_PongResp_1001000_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.SyncProto.internal_static_protoFiles_PongResp_1001000_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.SyncProto.PongResp_1001000.class, proto.SyncProto.PongResp_1001000.Builder.class);
      }

      // Construct using proto.SyncProto.PongResp_1001000.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.SyncProto.internal_static_protoFiles_PongResp_1001000_descriptor;
      }

      public proto.SyncProto.PongResp_1001000 getDefaultInstanceForType() {
        return proto.SyncProto.PongResp_1001000.getDefaultInstance();
      }

      public proto.SyncProto.PongResp_1001000 build() {
        proto.SyncProto.PongResp_1001000 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.SyncProto.PongResp_1001000 buildPartial() {
        proto.SyncProto.PongResp_1001000 result = new proto.SyncProto.PongResp_1001000(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.SyncProto.PongResp_1001000) {
          return mergeFrom((proto.SyncProto.PongResp_1001000)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.SyncProto.PongResp_1001000 other) {
        if (other == proto.SyncProto.PongResp_1001000.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.SyncProto.PongResp_1001000 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.SyncProto.PongResp_1001000) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protoFiles.PongResp_1001000)
    }

    static {
      defaultInstance = new PongResp_1001000(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protoFiles.PongResp_1001000)
  }

  public interface positionSyncReq_1001006OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required float x = 1;
    /**
     * <code>required float x = 1;</code>
     */
    boolean hasX();
    /**
     * <code>required float x = 1;</code>
     */
    float getX();

    // required float y = 2;
    /**
     * <code>required float y = 2;</code>
     */
    boolean hasY();
    /**
     * <code>required float y = 2;</code>
     */
    float getY();

    // required float z = 3;
    /**
     * <code>required float z = 3;</code>
     */
    boolean hasZ();
    /**
     * <code>required float z = 3;</code>
     */
    float getZ();

    // required float ex = 4;
    /**
     * <code>required float ex = 4;</code>
     */
    boolean hasEx();
    /**
     * <code>required float ex = 4;</code>
     */
    float getEx();

    // required float ey = 5;
    /**
     * <code>required float ey = 5;</code>
     */
    boolean hasEy();
    /**
     * <code>required float ey = 5;</code>
     */
    float getEy();

    // required float ez = 6;
    /**
     * <code>required float ez = 6;</code>
     */
    boolean hasEz();
    /**
     * <code>required float ez = 6;</code>
     */
    float getEz();
  }
  /**
   * Protobuf type {@code protoFiles.positionSyncReq_1001006}
   *
   * <pre>
   *位置同步
   * </pre>
   */
  public static final class positionSyncReq_1001006 extends
      com.google.protobuf.GeneratedMessage
      implements positionSyncReq_1001006OrBuilder {
    // Use positionSyncReq_1001006.newBuilder() to construct.
    private positionSyncReq_1001006(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private positionSyncReq_1001006(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final positionSyncReq_1001006 defaultInstance;
    public static positionSyncReq_1001006 getDefaultInstance() {
      return defaultInstance;
    }

    public positionSyncReq_1001006 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private positionSyncReq_1001006(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              x_ = input.readFloat();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              y_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              z_ = input.readFloat();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              ex_ = input.readFloat();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000010;
              ey_ = input.readFloat();
              break;
            }
            case 53: {
              bitField0_ |= 0x00000020;
              ez_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.SyncProto.internal_static_protoFiles_positionSyncReq_1001006_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.SyncProto.internal_static_protoFiles_positionSyncReq_1001006_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.SyncProto.positionSyncReq_1001006.class, proto.SyncProto.positionSyncReq_1001006.Builder.class);
    }

    public static com.google.protobuf.Parser<positionSyncReq_1001006> PARSER =
        new com.google.protobuf.AbstractParser<positionSyncReq_1001006>() {
      public positionSyncReq_1001006 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new positionSyncReq_1001006(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<positionSyncReq_1001006> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required float x = 1;
    public static final int X_FIELD_NUMBER = 1;
    private float x_;
    /**
     * <code>required float x = 1;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required float x = 1;</code>
     */
    public float getX() {
      return x_;
    }

    // required float y = 2;
    public static final int Y_FIELD_NUMBER = 2;
    private float y_;
    /**
     * <code>required float y = 2;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float y = 2;</code>
     */
    public float getY() {
      return y_;
    }

    // required float z = 3;
    public static final int Z_FIELD_NUMBER = 3;
    private float z_;
    /**
     * <code>required float z = 3;</code>
     */
    public boolean hasZ() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required float z = 3;</code>
     */
    public float getZ() {
      return z_;
    }

    // required float ex = 4;
    public static final int EX_FIELD_NUMBER = 4;
    private float ex_;
    /**
     * <code>required float ex = 4;</code>
     */
    public boolean hasEx() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required float ex = 4;</code>
     */
    public float getEx() {
      return ex_;
    }

    // required float ey = 5;
    public static final int EY_FIELD_NUMBER = 5;
    private float ey_;
    /**
     * <code>required float ey = 5;</code>
     */
    public boolean hasEy() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required float ey = 5;</code>
     */
    public float getEy() {
      return ey_;
    }

    // required float ez = 6;
    public static final int EZ_FIELD_NUMBER = 6;
    private float ez_;
    /**
     * <code>required float ez = 6;</code>
     */
    public boolean hasEz() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required float ez = 6;</code>
     */
    public float getEz() {
      return ez_;
    }

    private void initFields() {
      x_ = 0F;
      y_ = 0F;
      z_ = 0F;
      ex_ = 0F;
      ey_ = 0F;
      ez_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasZ()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEx()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEy()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEz()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, z_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, ex_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeFloat(5, ey_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeFloat(6, ez_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, z_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, ex_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, ey_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, ez_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static proto.SyncProto.positionSyncReq_1001006 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.SyncProto.positionSyncReq_1001006 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.SyncProto.positionSyncReq_1001006 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.SyncProto.positionSyncReq_1001006 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.SyncProto.positionSyncReq_1001006 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.SyncProto.positionSyncReq_1001006 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.SyncProto.positionSyncReq_1001006 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.SyncProto.positionSyncReq_1001006 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.SyncProto.positionSyncReq_1001006 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.SyncProto.positionSyncReq_1001006 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.SyncProto.positionSyncReq_1001006 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoFiles.positionSyncReq_1001006}
     *
     * <pre>
     *位置同步
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements proto.SyncProto.positionSyncReq_1001006OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.SyncProto.internal_static_protoFiles_positionSyncReq_1001006_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.SyncProto.internal_static_protoFiles_positionSyncReq_1001006_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.SyncProto.positionSyncReq_1001006.class, proto.SyncProto.positionSyncReq_1001006.Builder.class);
      }

      // Construct using proto.SyncProto.positionSyncReq_1001006.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        x_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        z_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        ex_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        ey_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        ez_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.SyncProto.internal_static_protoFiles_positionSyncReq_1001006_descriptor;
      }

      public proto.SyncProto.positionSyncReq_1001006 getDefaultInstanceForType() {
        return proto.SyncProto.positionSyncReq_1001006.getDefaultInstance();
      }

      public proto.SyncProto.positionSyncReq_1001006 build() {
        proto.SyncProto.positionSyncReq_1001006 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.SyncProto.positionSyncReq_1001006 buildPartial() {
        proto.SyncProto.positionSyncReq_1001006 result = new proto.SyncProto.positionSyncReq_1001006(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.z_ = z_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.ex_ = ex_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.ey_ = ey_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.ez_ = ez_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.SyncProto.positionSyncReq_1001006) {
          return mergeFrom((proto.SyncProto.positionSyncReq_1001006)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.SyncProto.positionSyncReq_1001006 other) {
        if (other == proto.SyncProto.positionSyncReq_1001006.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasZ()) {
          setZ(other.getZ());
        }
        if (other.hasEx()) {
          setEx(other.getEx());
        }
        if (other.hasEy()) {
          setEy(other.getEy());
        }
        if (other.hasEz()) {
          setEz(other.getEz());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasX()) {
          
          return false;
        }
        if (!hasY()) {
          
          return false;
        }
        if (!hasZ()) {
          
          return false;
        }
        if (!hasEx()) {
          
          return false;
        }
        if (!hasEy()) {
          
          return false;
        }
        if (!hasEz()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.SyncProto.positionSyncReq_1001006 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.SyncProto.positionSyncReq_1001006) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required float x = 1;
      private float x_ ;
      /**
       * <code>required float x = 1;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required float x = 1;</code>
       */
      public float getX() {
        return x_;
      }
      /**
       * <code>required float x = 1;</code>
       */
      public Builder setX(float value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float x = 1;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0F;
        onChanged();
        return this;
      }

      // required float y = 2;
      private float y_ ;
      /**
       * <code>required float y = 2;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float y = 2;</code>
       */
      public float getY() {
        return y_;
      }
      /**
       * <code>required float y = 2;</code>
       */
      public Builder setY(float value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float y = 2;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0F;
        onChanged();
        return this;
      }

      // required float z = 3;
      private float z_ ;
      /**
       * <code>required float z = 3;</code>
       */
      public boolean hasZ() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required float z = 3;</code>
       */
      public float getZ() {
        return z_;
      }
      /**
       * <code>required float z = 3;</code>
       */
      public Builder setZ(float value) {
        bitField0_ |= 0x00000004;
        z_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float z = 3;</code>
       */
      public Builder clearZ() {
        bitField0_ = (bitField0_ & ~0x00000004);
        z_ = 0F;
        onChanged();
        return this;
      }

      // required float ex = 4;
      private float ex_ ;
      /**
       * <code>required float ex = 4;</code>
       */
      public boolean hasEx() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required float ex = 4;</code>
       */
      public float getEx() {
        return ex_;
      }
      /**
       * <code>required float ex = 4;</code>
       */
      public Builder setEx(float value) {
        bitField0_ |= 0x00000008;
        ex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float ex = 4;</code>
       */
      public Builder clearEx() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ex_ = 0F;
        onChanged();
        return this;
      }

      // required float ey = 5;
      private float ey_ ;
      /**
       * <code>required float ey = 5;</code>
       */
      public boolean hasEy() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required float ey = 5;</code>
       */
      public float getEy() {
        return ey_;
      }
      /**
       * <code>required float ey = 5;</code>
       */
      public Builder setEy(float value) {
        bitField0_ |= 0x00000010;
        ey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float ey = 5;</code>
       */
      public Builder clearEy() {
        bitField0_ = (bitField0_ & ~0x00000010);
        ey_ = 0F;
        onChanged();
        return this;
      }

      // required float ez = 6;
      private float ez_ ;
      /**
       * <code>required float ez = 6;</code>
       */
      public boolean hasEz() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required float ez = 6;</code>
       */
      public float getEz() {
        return ez_;
      }
      /**
       * <code>required float ez = 6;</code>
       */
      public Builder setEz(float value) {
        bitField0_ |= 0x00000020;
        ez_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float ez = 6;</code>
       */
      public Builder clearEz() {
        bitField0_ = (bitField0_ & ~0x00000020);
        ez_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protoFiles.positionSyncReq_1001006)
    }

    static {
      defaultInstance = new positionSyncReq_1001006(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protoFiles.positionSyncReq_1001006)
  }

  public interface positionSyncResp_1001006OrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code protoFiles.positionSyncResp_1001006}
   */
  public static final class positionSyncResp_1001006 extends
      com.google.protobuf.GeneratedMessage
      implements positionSyncResp_1001006OrBuilder {
    // Use positionSyncResp_1001006.newBuilder() to construct.
    private positionSyncResp_1001006(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private positionSyncResp_1001006(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final positionSyncResp_1001006 defaultInstance;
    public static positionSyncResp_1001006 getDefaultInstance() {
      return defaultInstance;
    }

    public positionSyncResp_1001006 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private positionSyncResp_1001006(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.SyncProto.internal_static_protoFiles_positionSyncResp_1001006_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.SyncProto.internal_static_protoFiles_positionSyncResp_1001006_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.SyncProto.positionSyncResp_1001006.class, proto.SyncProto.positionSyncResp_1001006.Builder.class);
    }

    public static com.google.protobuf.Parser<positionSyncResp_1001006> PARSER =
        new com.google.protobuf.AbstractParser<positionSyncResp_1001006>() {
      public positionSyncResp_1001006 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new positionSyncResp_1001006(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<positionSyncResp_1001006> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static proto.SyncProto.positionSyncResp_1001006 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.SyncProto.positionSyncResp_1001006 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.SyncProto.positionSyncResp_1001006 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.SyncProto.positionSyncResp_1001006 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.SyncProto.positionSyncResp_1001006 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.SyncProto.positionSyncResp_1001006 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.SyncProto.positionSyncResp_1001006 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.SyncProto.positionSyncResp_1001006 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.SyncProto.positionSyncResp_1001006 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.SyncProto.positionSyncResp_1001006 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.SyncProto.positionSyncResp_1001006 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoFiles.positionSyncResp_1001006}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements proto.SyncProto.positionSyncResp_1001006OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.SyncProto.internal_static_protoFiles_positionSyncResp_1001006_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.SyncProto.internal_static_protoFiles_positionSyncResp_1001006_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.SyncProto.positionSyncResp_1001006.class, proto.SyncProto.positionSyncResp_1001006.Builder.class);
      }

      // Construct using proto.SyncProto.positionSyncResp_1001006.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.SyncProto.internal_static_protoFiles_positionSyncResp_1001006_descriptor;
      }

      public proto.SyncProto.positionSyncResp_1001006 getDefaultInstanceForType() {
        return proto.SyncProto.positionSyncResp_1001006.getDefaultInstance();
      }

      public proto.SyncProto.positionSyncResp_1001006 build() {
        proto.SyncProto.positionSyncResp_1001006 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.SyncProto.positionSyncResp_1001006 buildPartial() {
        proto.SyncProto.positionSyncResp_1001006 result = new proto.SyncProto.positionSyncResp_1001006(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.SyncProto.positionSyncResp_1001006) {
          return mergeFrom((proto.SyncProto.positionSyncResp_1001006)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.SyncProto.positionSyncResp_1001006 other) {
        if (other == proto.SyncProto.positionSyncResp_1001006.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.SyncProto.positionSyncResp_1001006 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.SyncProto.positionSyncResp_1001006) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protoFiles.positionSyncResp_1001006)
    }

    static {
      defaultInstance = new positionSyncResp_1001006(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protoFiles.positionSyncResp_1001006)
  }

  public interface attackReq_1001007OrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code protoFiles.attackReq_1001007}
   *
   * <pre>
   *攻击
   * </pre>
   */
  public static final class attackReq_1001007 extends
      com.google.protobuf.GeneratedMessage
      implements attackReq_1001007OrBuilder {
    // Use attackReq_1001007.newBuilder() to construct.
    private attackReq_1001007(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private attackReq_1001007(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final attackReq_1001007 defaultInstance;
    public static attackReq_1001007 getDefaultInstance() {
      return defaultInstance;
    }

    public attackReq_1001007 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private attackReq_1001007(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.SyncProto.internal_static_protoFiles_attackReq_1001007_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.SyncProto.internal_static_protoFiles_attackReq_1001007_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.SyncProto.attackReq_1001007.class, proto.SyncProto.attackReq_1001007.Builder.class);
    }

    public static com.google.protobuf.Parser<attackReq_1001007> PARSER =
        new com.google.protobuf.AbstractParser<attackReq_1001007>() {
      public attackReq_1001007 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new attackReq_1001007(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<attackReq_1001007> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static proto.SyncProto.attackReq_1001007 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.SyncProto.attackReq_1001007 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.SyncProto.attackReq_1001007 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.SyncProto.attackReq_1001007 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.SyncProto.attackReq_1001007 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.SyncProto.attackReq_1001007 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.SyncProto.attackReq_1001007 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.SyncProto.attackReq_1001007 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.SyncProto.attackReq_1001007 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.SyncProto.attackReq_1001007 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.SyncProto.attackReq_1001007 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoFiles.attackReq_1001007}
     *
     * <pre>
     *攻击
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements proto.SyncProto.attackReq_1001007OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.SyncProto.internal_static_protoFiles_attackReq_1001007_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.SyncProto.internal_static_protoFiles_attackReq_1001007_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.SyncProto.attackReq_1001007.class, proto.SyncProto.attackReq_1001007.Builder.class);
      }

      // Construct using proto.SyncProto.attackReq_1001007.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.SyncProto.internal_static_protoFiles_attackReq_1001007_descriptor;
      }

      public proto.SyncProto.attackReq_1001007 getDefaultInstanceForType() {
        return proto.SyncProto.attackReq_1001007.getDefaultInstance();
      }

      public proto.SyncProto.attackReq_1001007 build() {
        proto.SyncProto.attackReq_1001007 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.SyncProto.attackReq_1001007 buildPartial() {
        proto.SyncProto.attackReq_1001007 result = new proto.SyncProto.attackReq_1001007(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.SyncProto.attackReq_1001007) {
          return mergeFrom((proto.SyncProto.attackReq_1001007)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.SyncProto.attackReq_1001007 other) {
        if (other == proto.SyncProto.attackReq_1001007.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.SyncProto.attackReq_1001007 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.SyncProto.attackReq_1001007) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protoFiles.attackReq_1001007)
    }

    static {
      defaultInstance = new attackReq_1001007(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protoFiles.attackReq_1001007)
  }

  public interface attackResp_1001007OrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code protoFiles.attackResp_1001007}
   */
  public static final class attackResp_1001007 extends
      com.google.protobuf.GeneratedMessage
      implements attackResp_1001007OrBuilder {
    // Use attackResp_1001007.newBuilder() to construct.
    private attackResp_1001007(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private attackResp_1001007(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final attackResp_1001007 defaultInstance;
    public static attackResp_1001007 getDefaultInstance() {
      return defaultInstance;
    }

    public attackResp_1001007 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private attackResp_1001007(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.SyncProto.internal_static_protoFiles_attackResp_1001007_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.SyncProto.internal_static_protoFiles_attackResp_1001007_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.SyncProto.attackResp_1001007.class, proto.SyncProto.attackResp_1001007.Builder.class);
    }

    public static com.google.protobuf.Parser<attackResp_1001007> PARSER =
        new com.google.protobuf.AbstractParser<attackResp_1001007>() {
      public attackResp_1001007 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new attackResp_1001007(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<attackResp_1001007> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static proto.SyncProto.attackResp_1001007 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.SyncProto.attackResp_1001007 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.SyncProto.attackResp_1001007 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.SyncProto.attackResp_1001007 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.SyncProto.attackResp_1001007 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.SyncProto.attackResp_1001007 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.SyncProto.attackResp_1001007 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.SyncProto.attackResp_1001007 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.SyncProto.attackResp_1001007 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.SyncProto.attackResp_1001007 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.SyncProto.attackResp_1001007 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoFiles.attackResp_1001007}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements proto.SyncProto.attackResp_1001007OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.SyncProto.internal_static_protoFiles_attackResp_1001007_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.SyncProto.internal_static_protoFiles_attackResp_1001007_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.SyncProto.attackResp_1001007.class, proto.SyncProto.attackResp_1001007.Builder.class);
      }

      // Construct using proto.SyncProto.attackResp_1001007.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.SyncProto.internal_static_protoFiles_attackResp_1001007_descriptor;
      }

      public proto.SyncProto.attackResp_1001007 getDefaultInstanceForType() {
        return proto.SyncProto.attackResp_1001007.getDefaultInstance();
      }

      public proto.SyncProto.attackResp_1001007 build() {
        proto.SyncProto.attackResp_1001007 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.SyncProto.attackResp_1001007 buildPartial() {
        proto.SyncProto.attackResp_1001007 result = new proto.SyncProto.attackResp_1001007(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.SyncProto.attackResp_1001007) {
          return mergeFrom((proto.SyncProto.attackResp_1001007)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.SyncProto.attackResp_1001007 other) {
        if (other == proto.SyncProto.attackResp_1001007.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.SyncProto.attackResp_1001007 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.SyncProto.attackResp_1001007) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protoFiles.attackResp_1001007)
    }

    static {
      defaultInstance = new attackResp_1001007(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protoFiles.attackResp_1001007)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protoFiles_PingReq_1001000_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protoFiles_PingReq_1001000_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protoFiles_PongResp_1001000_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protoFiles_PongResp_1001000_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protoFiles_positionSyncReq_1001006_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protoFiles_positionSyncReq_1001006_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protoFiles_positionSyncResp_1001006_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protoFiles_positionSyncResp_1001006_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protoFiles_attackReq_1001007_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protoFiles_attackReq_1001007_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protoFiles_attackResp_1001007_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protoFiles_attackResp_1001007_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017SyncProto.proto\022\nprotoFiles\"\021\n\017PingReq" +
      "_1001000\"\022\n\020PongResp_1001000\"^\n\027position" +
      "SyncReq_1001006\022\t\n\001x\030\001 \002(\002\022\t\n\001y\030\002 \002(\002\022\t\n" +
      "\001z\030\003 \002(\002\022\n\n\002ex\030\004 \002(\002\022\n\n\002ey\030\005 \002(\002\022\n\n\002ez\030\006" +
      " \002(\002\"\032\n\030positionSyncResp_1001006\"\023\n\021atta" +
      "ckReq_1001007\"\024\n\022attackResp_1001007B\022\n\005p" +
      "rotoB\tSyncProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protoFiles_PingReq_1001000_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protoFiles_PingReq_1001000_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protoFiles_PingReq_1001000_descriptor,
              new java.lang.String[] { });
          internal_static_protoFiles_PongResp_1001000_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protoFiles_PongResp_1001000_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protoFiles_PongResp_1001000_descriptor,
              new java.lang.String[] { });
          internal_static_protoFiles_positionSyncReq_1001006_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_protoFiles_positionSyncReq_1001006_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protoFiles_positionSyncReq_1001006_descriptor,
              new java.lang.String[] { "X", "Y", "Z", "Ex", "Ey", "Ez", });
          internal_static_protoFiles_positionSyncResp_1001006_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_protoFiles_positionSyncResp_1001006_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protoFiles_positionSyncResp_1001006_descriptor,
              new java.lang.String[] { });
          internal_static_protoFiles_attackReq_1001007_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_protoFiles_attackReq_1001007_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protoFiles_attackReq_1001007_descriptor,
              new java.lang.String[] { });
          internal_static_protoFiles_attackResp_1001007_descriptor =
            getDescriptor().getMessageTypes().get(5);
          internal_static_protoFiles_attackResp_1001007_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protoFiles_attackResp_1001007_descriptor,
              new java.lang.String[] { });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
